### ISSUE TITLE
[uploadgui] Form error feedback broken

### ISSUE THREAD

**Issue by mirzov** [ICOS-Carbon-Portal/meta#132]
May be related to Bootstrap 5 upgrade. For example, wrong timestamp format does not result in noticeable highlight of the input control containing the timestamp text. Also, the Upload button, when disabled, does not seem to provide tooltip with error summary (not sure if it ever did, though...)

**Comment by jonathanthiry** [comment]
I don't think there is an easy way to display feedback on the Upload button when it's disabled, so it probably never worked. I could enable the button from the start and highlight invalid fields when clicking it, would that be a good solution?
