### ISSUE TITLE
Add export to CSV/KML to station list at https://www.icos-cp.eu/observations/station-network 

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/meta#135]
Exports details of current selection in the station list

**Comment by mirzov** [comment]
Fixed in https://github.com/ICOS-Carbon-Portal/drupal/commit/63e097f635265dcab3570358c28a68dc7e7f279b , https://github.com/ICOS-Carbon-Portal/drupal/commit/cb392e8c4c98e6906d3c344ab2c3c4d68da20f0a , and https://github.com/ICOS-Carbon-Portal/static/commit/cb223c8bebe822fe6d0b1ce6a95ff0543ed22853
