### ISSUE TITLE
Scripting for upload of historic timeseries

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/meta#142]
Easier scripting of upload of historic timeseries for (non-)ICOS stations like Drought2018 and Winter2020 datasets

**Comment by mirzov** [comment]
Drought2018 [upload workbench](https://github.com/ICOS-Carbon-Portal/meta/tree/master/src/test/scala/se/lu/nateko/cp/meta/upload) has been updated to upload Warm Winter 2020, and a number of useful bash one-liners  for preparation of Fluxnet half-hourly files and metadata tables have been [added to the codebase](https://github.com/ICOS-Carbon-Portal/meta/blob/1c0bc641b51dcddb28b1a2c1af482d4798199f64/src/test/bash/oneLinersForFluxnet.sh). Warm Winter 2020 products have been published.
