### ISSUE TITLE
Add layer controls to the station map

### ISSUE THREAD

**Issue by jonathanthiry** [ICOS-Carbon-Portal/meta#153]
Layers could be individually hidden, especially useful when they are overlapping, like for https://meta.fieldsites.se/resources/stations/abisko

See: https://leafletjs.com/SlavaUkraini/examples/layers-control/

**Comment by FangSkillmarck** [comment]
Since it is possible to have overlapping areas on different polygons, then we'll make a overlay in the map control to give the user freedom to check the interested feature.
