### ISSUE TITLE
Station personnel roles incomplete and showing duplicates for many stations

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/meta#160]
Using https://meta.icos-cp.eu/sparqlclient/?q=Production%20stations%27%20people%20and%20roles&type=CSV gives duplicate entries for persons when presumably duplicate roles with same weight exist, thereby not showing the persons with the duplicate role. 
For ecosystems the query gives even sometimes 5 or more duplicates.
Examples for eco: 
BE-Bra,Brasschaat,Ivan,Janssens,Principal Investigator,-1,2018-01-01T11:00:00Z,
BE-Bra,Brasschaat,Ivan,Janssens,Principal Investigator,-1,2018-01-01T11:00:00Z,
BE-Bra,Brasschaat,Ivan,Janssens,Principal Investigator,-1,2018-01-01T11:00:00Z,
BE-Bra,Brasschaat,Ivan,Janssens,Principal Investigator,-1,2018-01-01T11:00:00Z,
BE-Bra,Brasschaat,Ivan,Janssens,Principal Investigator,-1,2018-01-01T11:00:00Z,
BE-Bra,Brasschaat,Ivan,Janssens,Principal Investigator,-1,2018-01-01T11:00:00Z,
BE-Bra,Brasschaat,Ivan,Janssens,Principal Investigator,-1,2018-01-01T11:00:00Z,
BE-Bra,Brasschaat,Ivan,Janssens,Principal Investigator,-1,2018-01-01T11:00:00Z,
BE-Bra,Brasschaat,Ivan,Janssens,Principal Investigator,-1,2018-01-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
BE-Dor,Dorinne,Bernard,Heinesch,Principal Investigator,-1,2015-10-01T11:00:00Z,
for Atm:
LUT,Lutjewad,Bert,Scheeren,Principal Investigator,70,2018-08-13T11:00:00Z,
LUT,Lutjewad,Bert,Scheeren,Principal Investigator,70,2018-08-13T11:00:00Z,
Should have also listed Huilin Chen here as PI

**Comment by mirzov** [comment]
Fixed in https://github.com/ICOS-Carbon-Portal/meta/commit/c754a8ca83c8b488b118711ca0e6dc7b64f81e69
