### ISSUE TITLE
Use weights to get correct order in data citation string for CP uploads

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/meta#170]
Add weights (e.g. 0-100) as attribute to a contributor/author of a data object uploaded by CP, default is 1. Use weight to order contributor in citation string author list. Allow upload GUI to change weights of contributors. Creator should now be repeated as contributor and creator should not be in author list, or also  creator get weight attribute also and is implicit part of contributors.

**Comment by ukarst** [comment]
The same should apply to upload of documents for which the order of authors currently seems to be random.
