### ISSUE TITLE
Support sensor redeployments on landing pages and in JSON

### ISSUE THREAD

**Issue by mirzov** [ICOS-Carbon-Portal/meta#198]
Concerns ETC METEOSENS data at the moment. Current landing page and JSON metadata are designed under the assumption that sensor deployments are fixed for every data object. This is not the case, variable could have gotten another sensor assigned and/or sensor position could have changed in the course of data acquisition for a single L1 or L2 data objects. The landing page should reflect that, and `instrumentDeployment` property in class `VarMeta` should be upgraded from type `Option[InstrumentDeployment]` to type `Option[Seq[InstrumentDeployment]]`

**Comment by klarakristina** [comment]
Fixed in https://github.com/ICOS-Carbon-Portal/meta/commit/f4fc2ba50999e3f543c6277a5cdec15001fab18d
