### ISSUE TITLE
Download button on the landing pages

### ISSUE THREAD

**Issue by mirzov** [ICOS-Carbon-Portal/meta#271]
It has been reported from the end users that it takes them a while to find the download button for a data/doc object. Maybe we should consider moving or duplicating it in more places? Or making it floating? For example, for document downloads on ICOS Cities the button is indeed inconspicuous: 

![image](https://github.com/ICOS-Carbon-Portal/meta/assets/666648/965b0486-f1b4-44d4-b7ac-7c8bafd53b38)

**Comment by jonathanthiry** [comment]
I changed the buttons color to make them more visible, see https://github.com/ICOS-Carbon-Portal/meta/commit/34e728a735ac941d9ee4a618a7e2c7b1393532ef and https://github.com/ICOS-Carbon-Portal/data/commit/6fc54c765eda6d2b1772311a6d036a9619f384be.

Example: https://citymeta.icos-cp.eu/objects/7kpOJE_huNJ2TP450l7fsU6C

I'm also planning to improve the page layout so the buttons are easier to find.

**Comment by mirzov** [comment]
Orange button is much more visible, closing the issue.
