### ISSUE TITLE
Add optional sampling point to L0 to L2 metadata

### ISSUE THREAD

**Issue by jonathanthiry** [ICOS-Carbon-Portal/meta#59]
Similar to level 3 spacial coverage, it should either be latitude/longitude coordinates or a reusable GeoFeature that could be selected from a dropdown in the upload gui.

**Comment by DrMaggie** [comment]
Excellent idea, Jonathan!

**Comment by jonathanthiry** [comment]
Fixed in https://github.com/ICOS-Carbon-Portal/meta/pull/63
