### ISSUE TITLE
Station and other acquisition metadata not set when attempting to update metadata of Drought 2018 ecosystem data

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/meta#61]
Attempt to add contributors to metadata in uploadgui fails as station CH-Cha is not set correctly (and not included in dropdown list) for data object https://meta.icos-cp.eu/objects/wGSIOST0QIgkTsRm6Iol-G0Q

**Comment by mirzov** [comment]
Fixed in 8b7600b (the station is on the least now)
