### ISSUE TITLE
HTML formatting on data description / metadata

### ISSUE THREAD

**Issue by THolding** [ICOS-Carbon-Portal/meta#81]
Feature request to add the ability to format data descriptions and metadata using HTML / markup. This would improve readability, encourage in-depth descriptions, and better support in-line citations to published work e.g. describing methodology or external data used.

**Comment by roger-groth** [comment]
Partially fulfilled by keeping line breaks in description. See example https://data.icos-cp.eu/portal/#%7B%22route%22%3A%22metadata%22%2C%22id%22%3A%22op1DplOmrKqJYBba6illya3G%22%7D. Links in description are automatically converted to HTML links so they can be clicked.

**Comment by jonathanthiry** [comment]
It could be nice to highlight links at least. Roger example doesn't provide this anymore: https://meta.icos-cp.eu/objects/op1DplOmrKqJYBba6illya3G.

**Comment by mirzov** [comment]
[Markdown](https://en.wikipedia.org/wiki/Markdown) is now supported in descriptions, thanks to @jonathanthiry  ([PR-275](https://github.com/ICOS-Carbon-Portal/meta/pull/275))
